### ISSUE TITLE
Akumanor Escape DX not work

### ISSUE THREAD

**Issue by siriusinko** [mashakos/OmniScaler#1]
And many other games don't work. They just do not start and that's it.  In Monster Truck Madness works, but the hotkeys (Reshade) don't work, just like with dgvoodoo.

**Comment by mashakos** [comment]
> And many other games don't work. They just do not start and that's it. In Monster Truck Madness works, but the hotkeys (Reshade) don't work, just like with dgvoodoo.

As always, make sure to update to the latest version and check the documentation on gamefs.ini

In the case of Akumanor Escape DX, it appears that the game's dev is setting the compatibility mode of the game internally to Windows XP. My utility requires a feature called DWM that is found in Windows from Vista up to Windows 10. Set your game's compatibility in its exe properties to Windows 8, after which you are to do the same for OmniScaler.exe, then try again. Attached is a screengrab with my latest version of the utility (v0.5.0a) with compatibility set to Windows 8
![test_aedx](https://user-images.githubusercontent.com/19247958/116636717-3e2da500-a962-11eb-8334-add79b931e5a.jpg)
