### ISSUE TITLE
Add the ability to add flags GameEXE argument.

### ISSUE THREAD

**Issue by updawg** [mashakos/OmniScaler#2]
It would be nice to have the ability to add command line style flags for the GameEXE argument. This way you can launch games that may require specific tweaks to run properly.

**Comment by mashakos** [comment]
No need! Here is how you add command line flags:

1. create a shortcut of OmniScaler.exe
2. In the shortcut properties, add your command line arguments

Try it out and let me know if it worked for you.

**Comment by updawg** [comment]
That works thank you! Also thanks for the super quick response!
