### ISSUE TITLE
Reshade buttons do not work to open the menu

### ISSUE THREAD

**Issue by siriusinko** [mashakos/OmniScaler#3]
Home (7) and other Home not work. With what it can be connected? If you put a preset in advance, everything will work, but I cannot get into the Reshade menu and change anything.

**Comment by mashakos** [comment]
This is because I have not yet implemented code that detdcts reshade's hotkey yet. It is in the works. For the time being edit reshade config files manually

**Comment by siriusinko** [comment]
> This is because I have not yet implemented code that detdcts reshade's hotkey yet. It is in the works. For the time being edit reshade config files manually

**Comment by siriusinko** [comment]
Manual editing is not a problem. It's just that the Reshade greeting does not disappear, which is what is annoying. Okay, we'll wait for the next release.
