### ISSUE TITLE
Scaling in Windows interferes with Omniscaler

### ISSUE THREAD

**Issue by saftle** [mashakos/OmniScaler#4]
It looks like Omniscaler has issues when scaling everything to 125% as an example in Windows. This produces different results when using omniscaler, when using the integer scale setting, and also when using overscan.

As a workaround, I changed the compatibility settings to the following:
![dpi](https://user-images.githubusercontent.com/852777/117511869-cdecd800-af8e-11eb-8d7a-d66f665db254.PNG)

**Comment by mashakos** [comment]
Thanks for pointing this out! Am in the process of putting up new release that is DPI aware. Appreciate you bringing this to my attention.

**Comment by saftle** [comment]
Awesome. Seems to works perfectly. Thank you so much for your continued work on this awesome program!
