### ISSUE TITLE
Complications running omniscaler with 32bit wine

### ISSUE THREAD

**Issue by mlysle** [mashakos/OmniScaler#5]
Old Win95/98 games should theoretically benefit from Omniscaler. These games often expect a 32-bit environment. They won't run on a modern 64-bit Windows installation even in Windows XP compatability mode. You can play these games using a 32-bit wine prefix on modern 64-bit Windows or Linux.

But omniscaler expects a 64-bit environment. It's not going to run under 32-bit wine.

So I can't run both omniscaler and these games within the same prefix. And that presents a pretty big problem.

**Comment by mashakos** [comment]
omniscaler is 64bit by design and there will not be a 32bit version.
